# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66834cdc681ca3fa4cae6760e1dab55dee28eca24ab59a0393557c50b6a301a2bea4a81bb8e33f28d61b1375908e2bc6605d927b9d904f666f2213f1afde064c

test:
  secret_key_base: ad5f184bbbf43a386bbfb5d876d70773516421497b2c477539032384d6585b3b4b05df7bc05915ac248c55d4332ec5600a16776884f863e226ee757e9a79d0d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
